### ISSUE TITLE
No support for nullish coalescing operator??

### ISSUE THREAD

**Issue by pbb72** [sindresorhus/gulp-strip-debug#28]
Sorry if I am missing the point, just getting started with gulp.

It seems to me gulp-strip-debug crashes on a nullish coalescing operator (`??`):

test.js:
```
const test = null ?? 42;
```

Output:
```
SyntaxError in plugin "gulp-strip-debug"
Message:
    Unexpected token ?
Details:
    index: 19
    lineNumber: 1
    column: 20
    fileName: [...]\test.js
    domainEmitter: [object Object]
    domainThrown: false
```
